#!/usr/bin/env node
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { parseArgs } from "node:util";
import { loadConfig } from "./config.js";
import { createLogger } from "./log.js";
import { runCycle, runSingleItem } from "./pipeline.js";
import { renderMessageText, type SlackMessage } from "./slack/message.js";
import { checkBotToken } from "./slack/post.js";

const log = createLogger("run");

/** Writes the rendered message plus the exact payload, so the artifact is reviewable and replayable. */
async function writeMessageFile(
  path: string,
  sourceUrl: string,
  message: SlackMessage,
  analyzer: string,
  channelId: string | undefined,
): Promise<void> {
  const channel = channelId ?? "$SLACK_CHANNEL_ID";
  const contents = `# Slack message: ${message.text}

Generated by \`npm run run -- --url ${sourceUrl}\` on ${new Date().toISOString()}.
Analyzer: ${analyzer}. Target channel: \`${channel}\`.

## As it renders in Slack

${renderMessageText(message)}

## Exact \`chat.postMessage\` payload

\`\`\`json
${JSON.stringify({ channel, ...message, unfurl_links: false, unfurl_media: false }, null, 2)}
\`\`\`
`;

  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents, "utf8");
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: {
      url: { type: "string" },
      out: { type: "string" },
      "check-slack": { type: "boolean" },
    },
    allowPositionals: false,
  });

  const config = loadConfig();
  const startedAt = Date.now();

  if (values["check-slack"]) {
    if (!config.slackBotToken) {
      log.error("SLACK_BOT_TOKEN is not set — there is no bot token to check");
      process.exitCode = 1;
      return;
    }
    const check = await checkBotToken(config.slackBotToken, config.httpTimeoutMs);
    if (check.ok) {
      log.info(`Slack bot token: ${check.detail}`);
      return;
    }
    log.error(`Slack bot token: ${check.detail}`);
    process.exitCode = 1;
    return;
  }

  const analyzerLabel = config.cursorApiKey
    ? `${config.cursorModel} via cursor ${config.cursorRuntime}`
    : "heuristic fallback";
  log.info(
    `starting run (dryRun=${config.dryRun}, database=${config.databaseUrl ? "postgres" : "memory"}, analyzer=${analyzerLabel})`,
  );

  if (values.url) {
    log.info(`single-item mode: ${values.url}`);
    const message = await runSingleItem(config, values.url);
    if (values.out) {
      await writeMessageFile(
        values.out,
        values.url,
        message,
        analyzerLabel,
        config.slackChannelId,
      );
      log.info(`wrote ${values.out}`);
    }
    log.info(`done in ${((Date.now() - startedAt) / 1000).toFixed(1)}s`);
    return;
  }

  const summary = await runCycle(config);
  const seconds = ((Date.now() - startedAt) / 1000).toFixed(1);

  const retried = summary.retried > 0 ? `, ${summary.retried} retried` : "";
  // Only mentioned when it happened: on most days the reviewer closes nothing,
  // and a "0 closed on review" on every line teaches people to skip the line.
  const closed =
    summary.issuesClosed > 0 ? ` (${summary.issuesClosed} closed on review)` : "";
  // Said only on a quiet day, where "0 posted" is the whole run and the reader
  // needs to know the channel heard about it anyway.
  const quiet = summary.quietDayPosted ? ", nothing new so the quiet-day note went out" : "";
  log.info(
    `done in ${seconds}s — ${summary.candidates} candidates, ${summary.newItems} new (${summary.seeded} seeded), ${summary.analyzed} analyzed${retried}, ${summary.issuesOpened} issues opened${closed}, ${summary.posted} posted${quiet}`,
  );
  for (const note of summary.notes) log.info(`note: ${note}`);
}

main().catch((error: unknown) => {
  log.error("run failed", error instanceof Error ? (error.stack ?? error.message) : error);
  process.exitCode = 1;
});
